### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by OmprakashRR** [BETALAB-team/EUReCA#4]
Hi. I am trying to use EUReCA in PyCharm with the Conda Eureca mod environment. However, the code is throwing an error message as given in the title. I am attaching the snapshot of the entire output here for your reference. Requesting to check whether this can be resolved
<img width="703" alt="Capture" src="https://user-images.githubusercontent.com/88714503/159414674-c1103193-0314-4fa7-bf4e-a60d8eedadf9.PNG">

**Comment by enrico-prataviera** [comment]
Hi @OmprakashRR 
Seems something linked pvlib.  
What version of pvlib is installed in your env? 0.7.2 should be the one. Eventually, try to uninstall it and install it again.
Are you running EUReCA on windows?

**Comment by OmprakashRR** [comment]
Thanks @enrico-prataviera. 0.7.2 is installed and yes, I am running it on windows
